apiVersion: v1
kind: Service
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan
spec:
  type: LoadBalancer
  ports:
    - port: 8012
      protocol: TCP
      targetPort: 80
  selector:
    app: hello-kenzan
    tier: hello-kenzan

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-kenzan
        tier: hello-kenzan
    spec:
      containers:
        - image: local.docker.cn:5000/hello-kenzan:latest
          name: hello-kenzan
          ports:
            - containerPort: 80
              name: hello-kenzan
